name: FloodTwitExt

dependencies:
  - docopt
  - matplotlib
  - numpy
  - Cython
  - tensorflow
  - requests
  - pip
  - pip:
      - geopy
      - pyshp
      - bs4
      - coala_utils
      - imgkit
      - TwitterSearch
      - fake_useragent
      - -e .
